---
- name: ensure a server is present and started
  vr_server:
    api_key: "{{key}}"
    #api_account: "{{account}}
    name: "{{ vr_server_name }}"
    hostname: "{{ vr_server_name }}"
    os: Ubuntu 16.04 x64
    #plan: 1024 MB RAM,25 GB SSD,1.00 TB BW
    plan: 2048 MB RAM,40 GB SSD,2.00 TB BW
    region: Singapore
    ssh_keys: "{{vultr_keys.vultr_ssh_key.id}}"
    state: present
  register: vultr_instances

- name: Add new droplet to inventory
  add_host:
      name: "{{vr_server_name}}"
      groups: vultr
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_host: "{{ vultr_instances.vultr_server.v4_main_ip }}"
      ansible_ssh_user: root
      ansible_ssh_password: "{{ vultr_instances.vultr_server.default_password }}"
      #ansible_ssh_private_key_file: "{{ do_ssh_private_key }}"

- name: Wait for to listen on port 22
  wait_for:
      state: started
      host: "{{ vultr_instances.vultr_server.v4_main_ip }}"
      port: 22