---
- name: ensure a server is present and started
  vr_server:
    name: "{{ vr_server_name }}"
    hostname: "{{ vr_server_name }}"
    os: Ubuntu 16.04 x64
    plan: 1024 MB RAM,25 GB SSD,1.00 TB BW
    region: Singapore
    state: started
  register: vultr_instances

- name: Add new droplet to inventory
  add_host:
      name: "{{vr_server_name}}"
      groups: vultr
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_host: "{{ vultr_instances.vultr_server.v4_main_ip }}"
      ansible_ssh_user: root
      ansible_ssh_password: "{{ vultr_instances.vultr_server.default_password }}"
      #ansible_ssh_private_key_file: "{{ do_ssh_private_key }}"

- name: Wait for to listen on port 22
  wait_for:
      state: started
      host: "{{ vultr_instances.vultr_server.v4_main_ip }}"
      port: 22

- name: Public IP Address
  debug:
      msg: your ip address is {{ vultr_instances.vultr_server.v4_main_ip }}

- name: Show root login
  debug:
      msg: root password is {{ vultr_instances.vultr_server.default_password }}
